config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  resources :users
  get '/check' => 'users#check'

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get '/index' => 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password  #モデルへのパスワード暗号化機能の実装のコード（bcryp）

  validates :name, presence: true   #空白は許可しない
  validates :email, presence: true ,uniqueness: true  #空白は許可しない  #被らない
  validates :password, presence: true,   #空白は許可しない
  length: {minimum: 6}   #最低６文字必要とする

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  end

end

app/controllers/sessions_cotroller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def edit
  end

  def check
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="top">
  <div class="background">
    <div class="container">
      <header>
        <div class="header-left">
          <img class="logo" src="/photo/logo.png" alt="">
        </div>
        <div class="header-right">
          <h2>ログイン  /  新規登録</h2>
        </div>
      </header>

      <div class="mein-wrapper">
        <h2 class="heading">FAMILY_TASK</h2>
        <p class="text">日々のタスクの管理・分析<br>コミュニケーションのサポート</p>

        <div class="btn-wrapper">
          <a href="#" class="btn">新規登録</a>
          <a href="#" class="btn">ログイン</a>
        </div>

      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Familytask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/check.html.erb
<div class="user-check">
  <div class="background">
    <div class="container">

      <div class="mein-wrapper">
        <div class="heading">
          <h2 >登録内容の確認</h2>
        </div>
        <div class="formbox">
          <%= form_with url: check_path ,method: :get do |form| %>
            <div class="form">
              <img class="image" src="/photo/user.jpeg" alt="">
            </div>

            <div class="form">
              <div class="name">
               <p> お名前</p><br>
               <h2>山田 太郎</h2>
              </div>
            </div>

            <div class="form">
              <div class="title">
                <p> メールアドレス</p><br>
              </div>
              <h2>yamada_tarou@gmail.com</h2>
            </div>

            <div class="form">
              <div class="password">
                <p> パスワード</p><br>
                <h2>123456789</h2>
              </div>
            </div>

            <div class="btn-wrapper">
              <%= form.submit "登録する"%>   
              <a href="#">修正する</a>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/users/chek.html.erb
<h2>チェックページ</h2>

app/views/users/edit.html.erb
<h1>Users#edit</h1>

app/views/users/new.html.erb
<div class="user-new">
  <div class="background">
    <div class="container">

      <div class="mein-wrapper">
        <div class="heading">
          <h2 >新規登録</h2>
        </div>
        <div class="formbox">
          <%= form_with url: check_path ,method: :get do |form| %>
            <div class="form">
              <div class="form-title">
                <%=form.label :プロフィールアイコン %><br>
              </div>
              <div class="file-form">
                <%=form.file_field :プロフィールアイコン %>
              </div>
            </div>

            <div class="form">
              <div class="form-title">
                <%=form.label :お名前 %><br>
              </div>
              <%=form.text_field :お名前 %>
            </div>

            <div class="form">
              <div class="form-title">
                <%=form.label :メールアドレス %><br>
              </div>
              <%=form.email_field :メールアドレス %>
            </div>

            <div class="form">
              <div class="form-title">
                <%=form.label :パスワード %><br>
              </div>
              <%=form.password_field :パスワード %>
            </div>

            <div class="form">
              <div class="form-title">
                <%=form.label :パスワード（確認） %><br>
              </div>
              <%=form.password_field :パスワード（確認） %>
            </div>
            <div class="btn-wrapper">
              <%= form.submit "登録する"%>   
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>